// Generated by IcedCoffeeScript 1.2.0s

(function(global, exports) {
  "use strict";    
    var entryPoint, font, iced, toggleBaseline, util,
    __slice = [].slice;

  window.iced = {
    Deferrals: (function() {

      function _Class(_arg) {
        this.continuation = _arg;
        this.count = 1;
        this.ret = null;
      }

      _Class.prototype._fulfill = function() {
        if (!--this.count) return this.continuation(this.ret);
      };

      _Class.prototype.defer = function(defer_params) {
        var _this = this;
        ++this.count;
        return function() {
          var inner_params, _ref;
          inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          if (defer_params != null) {
            if ((_ref = defer_params.assign_fn) != null) {
              _ref.apply(null, inner_params);
            }
          }
          return _this._fulfill();
        };
      };

      return _Class;

    })(),
    findDeferral: function() {
      return null;
    }
  };

  iced = global.iced;

  util = global.jaap.util;

  font = global.jaap.font;

  toggleBaseline = function() {
    var elem;
    elem = document.querySelector('#baseline-checkbox');
    if (elem) return elem.checked = !elem.checked;
  };

  entryPoint = function() {
    if (top !== window) return;
    util.onKeyUp('B', toggleBaseline);
    return util.onKeyUp('T', font.getMetrics);
  };

  entryPoint();

}).call(undefined, window, (function() {
  if (window.jaap == null) window.jaap = {};
  return window.jaap;
})());
