// Generated by IcedCoffeeScript 1.2.0s

(function(global, exports) {
  "use strict";    
    var ajax, diagnose, dom, entryPoint, font, iced, keys, toggleBaseline, util, _ref;

  iced = global.iced, (_ref = global.jaap, util = _ref.util, ajax = _ref.ajax, dom = _ref.dom, keys = _ref.keys, font = _ref.font);

  toggleBaseline = function() {
    return dom.toggleClass(document.body, 'baseline');
  };

  diagnose = function() {
    var body, get, ppgd;
    body = document.body;
    ppgd = parseFloat(window.getComputedStyle(body).lineHeight);
    get = function(name) {
      var elem, height, isHeightWholeNumber, ppem, pplh, style;
      style = {
        fontSize: '0',
        lineHeight: '0'
      };
      elem = document.querySelector(name);
      if (elem) style = window.getComputedStyle(elem);
      ppem = parseFloat(style.fontSize);
      pplh = parseFloat(style.lineHeight);
      height = elem.getBoundingClientRect().height;
      isHeightWholeNumber = name === 'html' || name === 'body' ? "" : " " + height + " / " + ppgd + " = " + (height / ppgd);
      return "" + ppem + "/" + pplh + isHeightWholeNumber + ": " + name + "<br/>";
    };
    return document.querySelector('#dimensions').innerHTML = "" + (get('html')) + "\n" + (get('body')) + "\n" + (get('p')) + "\n" + (get('h1')) + "\n" + (get('h2')) + "\n" + (get('h3')) + "\n" + (get('.small')) + "\nviewport: " + window.innerWidth + "\u00D7" + window.innerHeight + ", " + window.orientation + "<br/>\nbody:     " + body.offsetWidth + "\u00D7" + body.offsetWidth;
  };

  entryPoint = function() {
    var repeated_diagnose;
    if (top !== window) return;
    keys.on('b', toggleBaseline);
    keys.on('shift+t', font.getMetrics);
    keys.on('shift+d', diagnose);
    keys.on('shift+c', dom.verifyCss);
    return repeated_diagnose = function() {
      var every_num_ms;
      every_num_ms = 300;
      diagnose();
      return util.delay(every_num_ms, repeated_diagnose);
    };
  };

  entryPoint();

}).call(undefined, window, (function() {
  if (window.jaap == null) window.jaap = {};
  return window.jaap;
})());
