// Generated by IcedCoffeeScript 1.2.0s

/*
  console.log ,{ arg }

  f0 = (arg) ->
    2 * arg

  m0 = (arg) -^
    -`
      console.log ,{ arg }
    -` "hello"
    (-` console.log ,{ arg }) for idx in [0...13]
  
  f0 3 + 5
  m0 3 + 5

  "fdsafsda"
*/


(function() {



}).call(this);
