// Generated by IcedCoffeeScript 1.2.0s

(function(global, exports) {
  "use strict";    
    var addEvent, assignKey, clearModifier, dispatch, k, resetModifiers, _MAP, _MODIFIERS, _handlers, _i, _mods,
    __hasProp = {}.hasOwnProperty,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  dispatch = function(event) {
    var handler, i, k, key, modifiersMatch, _ref, _results;
    key = event.keyCode;
    if (key === 93 || key === 224) key = 91;
    if (key in _mods) {
      _mods[key] = true;
      for (k in _MODIFIERS) {
        if (_MODIFIERS[k] === key) assignKey[k] = true;
      }
      return;
    }
    if (!assignKey.filter.call(this, event)) return;
    if (!(key in _handlers)) return;
    i = 0;
    _results = [];
    while (i < _handlers[key].length) {
      handler = _handlers[key][i];
      modifiersMatch = handler.mods.length > 0;
      for (k in _mods) {
        if (!__hasProp.call(_mods, k)) continue;
        if ((!_mods[k] && __indexOf.call(handler.mods, +k) >= 0) || (_mods[k] && (_ref = !+k, __indexOf.call(handler.mods, _ref) >= 0))) {
          modifiersMatch = false;
        }
      }
      if ((handler.mods.length === 0 && !_mods[16] && !_mods[18] && !_mods[17] && !_mods[91]) || modifiersMatch) {
        if (handler.method(event, handler) === false) {
          if (event.preventDefault) {
            event.preventDefault();
          } else {
            event.returnValue = false;
          }
          if (event.stopPropagation) event.stopPropagation();
          if (event.cancelBubble) event.cancelBubble = true;
        }
      }
      _results.push(i++);
    }
    return _results;
  };

  clearModifier = function(event) {
    var k, key;
    key = event.keyCode;
    if (key === 93 || key === 224) key = 91;
    if (key in _mods) {
      _mods[key] = false;
      for (k in _MODIFIERS) {
        if (_MODIFIERS[k] === key) assignKey[k] = false;
      }
    }
  };

  resetModifiers = function() {
    var k;
    for (k in _mods) {
      _mods[k] = false;
    }
    for (k in _MODIFIERS) {
      assignKey[k] = false;
    }
  };

  assignKey = function(key, method) {
    var i, keys, mi, mods, _results;
    key = key.replace(/\s/g, "");
    keys = key.split(",");
    if (keys[keys.length - 1] === "") keys[keys.length - 2] += ",";
    i = 0;
    _results = [];
    while (i < keys.length) {
      mods = [];
      key = keys[i].split("+");
      if (key.length > 1) {
        mods = key.slice(0, key.length - 1);
        mi = 0;
        while (mi < mods.length) {
          mods[mi] = _MODIFIERS[mods[mi]];
          mi++;
        }
        key = [key[key.length - 1]];
      }
      key = key[0];
      key = _MAP[key] || key.toUpperCase().charCodeAt(0);
      if (!(key in _handlers)) _handlers[key] = [];
      _handlers[key].push({
        shortcut: keys[i],
        method: method,
        key: keys[i],
        mods: mods
      });
      _results.push(i++);
    }
    return _results;
  };

  assignKey.filter = function(event) {
    var tagName;
    tagName = (event.target || event.srcElement).tagName;
    return !(tagName === "INPUT" || tagName === "SELECT" || tagName === "TEXTAREA");
  };

  addEvent = function(object, event, method) {
    if (object.addEventListener) {
      return object.addEventListener(event, method, false);
    } else if (object.attachEvent) {
      return object.attachEvent("on" + event, function() {
        return method(window.event);
      });
    }
  };

  _handlers = {};

  _mods = {
    16: false,
    18: false,
    17: false,
    91: false
  };

  _MODIFIERS = {
    shift: 16,
    alt: 18,
    option: 18,
    ctrl: 17,
    command: 91
  };

  for (k = _i = 1; _i < 20; k = ++_i) {
    _MODIFIERS["f" + k] = 111 + k;
  }

  _MAP = {
    backspace: 8,
    tab: 9,
    clear: 12,
    enter: 13,
    "return": 13,
    esc: 27,
    escape: 27,
    space: 32,
    left: 37,
    up: 38,
    right: 39,
    down: 40,
    del: 46,
    "delete": 46,
    home: 36,
    end: 35,
    pageup: 33,
    pagedown: 34,
    ",": 188,
    ".": 190,
    "/": 191,
    "`": 192,
    "-": 189,
    "=": 187,
    ";": 186,
    "'": 222,
    "[": 219,
    "]": 221,
    "\\": 220
  };

  for (k in _MODIFIERS) {
    if (!__hasProp.call(_MODIFIERS, k)) continue;
    assignKey[k] = false;
  }

  addEvent(document, "keydown", dispatch);

  addEvent(document, "keyup", clearModifier);

  addEvent(window, "focus", resetModifiers);

  exports.on = assignKey;

}).call(undefined, window, (function() {
  var _base;
  if (window.jaap == null) window.jaap = {};
  if ((_base = window.jaap).keys == null) _base.keys = {};
  return window.jaap.keys;
})());
