// Generated by IcedCoffeeScript 1.2.0r
  var f0;

  console.log(arg);

  f0 = function(arg) {
    return 2 * arg;
  };

  /*macro m0 defined
  */


  f0(3 + 5);

  console.log(3 + 5);
  "hello";

  console.log(3 + 5);
  console.log(3 + 5);
  console.log(3 + 5);
  console.log(3 + 5);
  console.log(3 + 5);
  console.log(3 + 5);
  console.log(3 + 5);
  console.log(3 + 5);
  console.log(3 + 5);
  console.log(3 + 5);
  console.log(3 + 5);
  console.log(3 + 5);
  console.log(3 + 5);

  "fdsafsda";

