// Generated by IcedCoffeeScript 1.2.0s

(function(global, exports) {
  "use strict";    
    var delay, isNumber, isUndefined, soon, tail, time;

  exports.time = time = function(fun) {
    var start;
    start = new Date();
    fun();
    return new Date() - start;
  };

  exports.isNumber = isNumber = function(obj) {
    return (obj === +obj) || Object.prototype.toString.call(obj) === '[object Number]';
  };

  exports.isUndefined = isUndefined = function(obj) {
    return typeof obj === 'undefined';
  };

  exports.delay = delay = function(func, wait) {
    var args;
    args = this.tail(arguments, 2);
    return setTimeout((function() {
      return func.apply(func, args);
    }), wait);
  };

  exports.soon = soon = function(func) {
    return this.delay.apply(this, [func, 1].concat(this.tail(arguments)));
  };

  exports.tail = tail = function(array, index) {
    return Array.prototype.slice.call(array, this.isUndefined(index) ? 1 : index);
  };

}).call(undefined, window, (function() {
  var _base;
  if (window.jaap == null) window.jaap = {};
  if ((_base = window.jaap).util == null) _base.util = {};
  return window.jaap.util;
})());
